language: cpp
sudo: required
dist: trusty

# get libbtbb
before_script:
  - git clone https://github.com/greatscottgadgets/libbtbb /tmp/libbtbb
  - mkdir /tmp/libbtbb/build
  - pushd /tmp/libbtbb/build
  - cmake ..
  - make
  - sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test

addons:
  apt:
    packages:
    - cmake
    - swig3.0
    - gnuradio-dev
      # and gnuradio-dev's dependencies, which aren't in trusty
    - libboost-date-time-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-test-dev
    - libboost-thread-dev
    - libcppunit-dev
    - libfftw3-dev
    - liblog4cpp5-dev
    - python-dev
    - python-numpy

